#
# Message sent when the player doesnt have permission for
# a channel or any command of the plugin.
#
no_permission: '&cYou do not have permission!'

#
# Message sent to the sender saying the amount of players
# who readed the player message.
#
amount_readed: '&5<amount> players saw your message!'

#
# Message sent when no one readed the player message
#
no_one: '&cNo one readed your message! :c'

#
# When console or any non-player tries to execute a command they shouldn't
#
players_only: '&cOnly players can execute this command!'

#
# Sent when player incorrectly uses /channel
#
channel_command_usage: '&cUsage: /ch <channel>'

#
# Sent when the player tries to do chat without any text
#
channel_usage_message: '&cUsage: /{command} <message>'

#
# Message sent when the player changes the main channel with /ch
# Placeholders:
# <channelName> - Full name of the channel
# <channelCommand> - Command of the channel
#
channel_changed: '&aChannel changed to <channelName> - <channelCommand>'

#
# Sent when the player do not have permission to use a channel or somehow the channel do not exist
#
invalid_channel: '&cInvalid channel!'

#
# Text sent when plugin is reloaded
#     NOT IMPLEMENTED YET!
#
plugin_reloaded: '&aPlugin reloaded.'

#
# Should all chat messages be sent to console?
#
log_to_console: true

#
# Message send to console when someone uses chat
# Placeholders:
# <channel> - Full channel name
# <channelCmd> - Channel command
# <player> - The player who sent the message
# <message> - The message itself
# Any PAPI placeholder
#
console_log: '[<channel>] %luckperms_prefix%<player>> <message>'

#
# Spam limit in caracter
#
spam_limit: 10

#
# Message canceled because contain spam
#
message_canceled_spam: "&aMessage canceled because contain spam."

#
# Message canceled because it has already been sent
#
message_canceled_flood: "&aYou cannot send a message like the previous message."

#
# Enable or disable plugin components here
# Every module have its own configuration file
# so you will not get distracted with useless or unrelated
# things while setting up the plugin.
#
modules:
    #
    # Chat color module
    # Players can choose their own chatcolor
    # either normal (&c) or hexadecimal (#4DC3FF)
    #
    chatcolor: true
    #
    # DiscordSRV integration
    # if you would like to enable integration with DiscordSRV,
    # enable this option.
    # The plugin will send chat messages from channels as configured in DiscordSRV.
    # but it will NOT receive messages from Discord and send to the chat.
    #
    discordsrv: true
    #
    # Chat focus modules
    # Players can choose a chat to default speak on or
    # Optionally, force chat worlds can be set-up
    #
    focus: true
    #
    # Chat filter and replacer module
    # Messages containing specific pre-defined words will be replaced
    # Disable if you don't need this
    #
    filter: true
    #
    # Prevents using too many repeated characters
    #
    prevent_spam: false
    #
    # Avoid repeating phrases in the chat
    #
    prevent_flood: false
    #
    # Allows you to send messages in capital letters.
    # If disabled, the message will be in lowercase.
    #
    allow_uppercase: true