#
# Message sent when the player doesnt have permission for
# a channel or any command of the plugin.
#
no_permission: '&cVocê não tem permissão!'

#
# Message sent to the sender saying the amount of players
# who readed the player message.
#
amount_readed: '&5<amount> jogadores leram sua mensagem!'

#
# Message sent when no one readed the player message
#
no_one: '&cNinguém leu sua mensagem! :c'

#
# Sent when the player tries to do chat without any text
#
channel_usage_message: '&cUso: /{command} <mensagem>'

#
# Text sent when plugin is reloaded
#
plugin_reloaded: '&aPlugin recarregado.'

#
# Should all chat messages be sent to console?
#
log_to_console: true

#
# Message send to console on chat
# Placeholders:
# <channel> - Full channel name
# <channelCmd> - Channel command
# <player> - The player who sent the message
# <message> - The message itself
# Any PAPI placeholder
#
console_log: '[<channel>] %luckperms_prefix%<player>> <message>'

#
# Enable or disable plugin components here
# Every module have its own configuration file
# so you will not get distracted with useless or unrelated
# things while setting up things.
#
modules:
    #
    # Chat color module
    # Players can choose their own chatcolor
    # either normal (&c) or hexadecimal (#4DC3FF)
    #
    chatcolor: true
    # Chat focus modules
    # Players can choose a chat to default speak on or
    # Optionally, force chat worlds can be set-up
    focus: true