name: ${project.name}
version: ${project.version}
api-version: 1.13
main: me.luucx7.simplexchat.SimplexChat
author: Luucx7
depend: [PlaceholderAPI]
commands:
    chatcor:
        aliases: [chatcolor, chatcor]
    simplexchat:
